function pos_MCP = findMCPpos(CMC_AA,CMC_FE,l_meta,xCMC,yCMC,zCMC)
%FINDMCPPOS
%    POS_MCP = FINDMCPPOS(CMC_AA,CMC_FE,L_META,XCMC,YCMC,ZCMC)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Feb-2018 09:30:41

t2 = cos(CMC_AA);
t3 = t2.*6.123233995736766e-17;
t4 = sin(CMC_AA);
t5 = cos(CMC_FE);
t6 = t4.*3.749399456654644e-33;
t7 = t3+t6;
t8 = sin(CMC_FE);
t9 = t4.*6.123233995736766e-17;
pos_MCP = [xCMC-l_meta.*t7.*t8+l_meta.*t5.*(t3-t4);yCMC+l_meta.*t5.*t7+l_meta.*t8.*(t2.*2.295845021658468e-49-t6+1.0);zCMC-l_meta.*t8.*(t2.*(-3.749399456654644e-33)+t9+6.123233995736766e-17)+l_meta.*t5.*(t2+t9);1.0];
