function matrix = DH_matrix(d_i, theta_i, a_i, alpha_i)
%This function construct the DH transformation given DH parameters. 
%   
DH_first = [cos(theta_i), -sin(theta_i), 0, 0; ...
            sin(theta_i),  cos(theta_i), 0, 0; ...
            0           , 0            , 1, d_i; ...
            0           , 0            , 0, 1];
        
DH_second = [1,            0,             0, a_i; ...
             0, cos(alpha_i), -sin(alpha_i), 0; ...
             0, sin(alpha_i),  cos(alpha_i), 0; ...
             0,            0,             0, 1];
         
matrix = DH_first*DH_second;
end
