function MCP = findMCP_pos(CMC_AA,CMC_FE,l_meta,xCMC,yCMC,zCMC)
%FINDMCP_POS
%    MCP = FINDMCP_POS(CMC_AA,CMC_FE,L_META,XCMC,YCMC,ZCMC)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Feb-2018 11:39:36

t2 = cos(CMC_AA);
t3 = sin(CMC_FE);
t4 = cos(CMC_FE);
t5 = sin(CMC_AA);
MCP = [xCMC-l_meta.*t2.*t4+l_meta.*t3.*t5.*6.123233995736766e-17;yCMC-l_meta.*t2.*t3.*6.123233995736766e-17-l_meta.*t4.*t5;zCMC-l_meta.*t3;1.0];
