function MCP_FE_s = findMCP_FE(l_dist,xK,xMCP,xPIP,yK,yMCP,yPIP,zK,zMCP,zPIP)
%FINDMCP_FE
%    MCP_FE_S = FINDMCP_FE(L_DIST,XK,XMCP,XPIP,YK,YMCP,YPIP,ZK,ZMCP,ZPIP)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Feb-2018 16:40:36

t2 = xK-xMCP;
t3 = yK-yMCP;
t4 = zK-zMCP;
t5 = t2.^2;
t6 = xK-xPIP;
t7 = t3.^2;
t8 = yK-yPIP;
t9 = t4.^2;
t10 = zK-zPIP;
MCP_FE_s = acos((1.0./sqrt(t5+t7+t9).*(t5.*(-1.0./2.0)-t7.*(1.0./2.0)-t9.*(1.0./2.0)+l_dist.^2.*(1.0./2.0)+t6.^2.*(1.0./2.0)+t8.^2.*(1.0./2.0)+t10.^2.*(1.0./2.0)))./l_dist);
