function CodeDefine() { 
this.def = new Array();
this.def["stopRequested"] = {file: "ert_main_cpp.html",line:15,type:"var"};
this.def["runModel"] = {file: "ert_main_cpp.html",line:16,type:"var"};
this.def["stopSem"] = {file: "ert_main_cpp.html",line:17,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_cpp.html",line:18,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_cpp.html",line:19,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_cpp.html",line:20,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_cpp.html",line:21,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_cpp.html",line:22,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_cpp.html",line:23,type:"fcn"};
this.def["exitFcn"] = {file: "ert_main_cpp.html",line:43,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_cpp.html",line:49,type:"fcn"};
this.def["main"] = {file: "ert_main_cpp.html",line:66,type:"fcn"};
this.def["toUdp_B"] = {file: "toUdp_cpp.html",line:26,type:"var"};
this.def["toUdp_DW"] = {file: "toUdp_cpp.html",line:29,type:"var"};
this.def["toUdp_M_"] = {file: "toUdp_cpp.html",line:32,type:"var"};
this.def["toUdp_M"] = {file: "toUdp_cpp.html",line:33,type:"var"};
this.def["rt_roundf_snf"] = {file: "toUdp_cpp.html",line:34,type:"fcn"};
this.def["toUdp_step"] = {file: "toUdp_cpp.html",line:53,type:"fcn"};
this.def["toUdp_initialize"] = {file: "toUdp_cpp.html",line:148,type:"fcn"};
this.def["toUdp_terminate"] = {file: "toUdp_cpp.html",line:257,type:"fcn"};
this.def["B_toUdp_T"] = {file: "toUdp_h.html",line:68,type:"type"};
this.def["DW_toUdp_T"] = {file: "toUdp_h.html",line:78,type:"type"};
this.def["SL_Bus_toUdp_std_msgs_Float64"] = {file: "toUdp_types_h.html",line:30,type:"type"};
this.def["robotics_slros_internal_block_T"] = {file: "toUdp_types_h.html",line:39,type:"type"};
this.def["robotics_slros_internal_blo_a_T"] = {file: "toUdp_types_h.html",line:48,type:"type"};
this.def["P_toUdp_T"] = {file: "toUdp_types_h.html",line:53,type:"type"};
this.def["RT_MODEL_toUdp_T"] = {file: "toUdp_types_h.html",line:56,type:"type"};
this.def["toUdp_P"] = {file: "toUdp_data_cpp.html",line:25,type:"var"};
this.def["long_T"] = {file: "multiword_types_h.html",line:28,type:"type"};
this.def["int64m_T"] = {file: "multiword_types_h.html",line:35,type:"type"};
this.def["cint64m_T"] = {file: "multiword_types_h.html",line:40,type:"type"};
this.def["uint64m_T"] = {file: "multiword_types_h.html",line:44,type:"type"};
this.def["cuint64m_T"] = {file: "multiword_types_h.html",line:49,type:"type"};
this.def["int96m_T"] = {file: "multiword_types_h.html",line:53,type:"type"};
this.def["cint96m_T"] = {file: "multiword_types_h.html",line:58,type:"type"};
this.def["uint96m_T"] = {file: "multiword_types_h.html",line:62,type:"type"};
this.def["cuint96m_T"] = {file: "multiword_types_h.html",line:67,type:"type"};
this.def["int128m_T"] = {file: "multiword_types_h.html",line:71,type:"type"};
this.def["cint128m_T"] = {file: "multiword_types_h.html",line:76,type:"type"};
this.def["uint128m_T"] = {file: "multiword_types_h.html",line:80,type:"type"};
this.def["cuint128m_T"] = {file: "multiword_types_h.html",line:85,type:"type"};
this.def["int160m_T"] = {file: "multiword_types_h.html",line:89,type:"type"};
this.def["cint160m_T"] = {file: "multiword_types_h.html",line:94,type:"type"};
this.def["uint160m_T"] = {file: "multiword_types_h.html",line:98,type:"type"};
this.def["cuint160m_T"] = {file: "multiword_types_h.html",line:103,type:"type"};
this.def["int192m_T"] = {file: "multiword_types_h.html",line:107,type:"type"};
this.def["cint192m_T"] = {file: "multiword_types_h.html",line:112,type:"type"};
this.def["uint192m_T"] = {file: "multiword_types_h.html",line:116,type:"type"};
this.def["cuint192m_T"] = {file: "multiword_types_h.html",line:121,type:"type"};
this.def["int224m_T"] = {file: "multiword_types_h.html",line:125,type:"type"};
this.def["cint224m_T"] = {file: "multiword_types_h.html",line:130,type:"type"};
this.def["uint224m_T"] = {file: "multiword_types_h.html",line:134,type:"type"};
this.def["cuint224m_T"] = {file: "multiword_types_h.html",line:139,type:"type"};
this.def["int256m_T"] = {file: "multiword_types_h.html",line:143,type:"type"};
this.def["cint256m_T"] = {file: "multiword_types_h.html",line:148,type:"type"};
this.def["uint256m_T"] = {file: "multiword_types_h.html",line:152,type:"type"};
this.def["cuint256m_T"] = {file: "multiword_types_h.html",line:157,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:28,type:"type"};
this.def["libName_Network"] = {file: "DAHostLib_Network_c.html",line:11,type:"var"};
this.def["libName_Network"] = {file: "DAHostLib_Network_c.html",line:11,type:"var"};
this.def["libName_Network"] = {file: "DAHostLib_Network_c.html",line:11,type:"var"};
this.def["CreateUDPInterface"] = {file: "DAHostLib_Network_c.html",line:23,type:"fcn"};
this.def["DestroyUDPInterface"] = {file: "DAHostLib_Network_c.html",line:31,type:"fcn"};
this.def["LibCreate_Network"] = {file: "DAHostLib_Network_c.html",line:41,type:"fcn"};
this.def["LibUpdate_Network"] = {file: "DAHostLib_Network_c.html",line:49,type:"fcn"};
this.def["LibOutputs_Network"] = {file: "DAHostLib_Network_c.html",line:55,type:"fcn"};
this.def["NetworkInputOrOutput"] = {file: "DAHostLib_Network_h.html",line:18,type:"type"};
this.def[")"] = {file: "DAHostLib_Network_h.html",line:24,type:"type"};
this.def[")"] = {file: "DAHostLib_Network_h.html",line:25,type:"type"};
this.def[")"] = {file: "DAHostLib_Network_h.html",line:26,type:"type"};
this.def["CreateHostLibrary"] = {file: "DAHostLib_rtw_c.html",line:13,type:"fcn"};
this.def["DestroyHostLibrary"] = {file: "DAHostLib_rtw_c.html",line:78,type:"fcn"};
this.def["LibStart"] = {file: "DAHostLib_rtw_c.html",line:92,type:"fcn"};
this.def["LibReset"] = {file: "DAHostLib_rtw_c.html",line:99,type:"fcn"};
this.def["LibTerminate"] = {file: "DAHostLib_rtw_c.html",line:106,type:"fcn"};
this.def["LibDestroy"] = {file: "DAHostLib_rtw_c.html",line:113,type:"fcn"};
this.def["LibError"] = {file: "DAHostLib_rtw_c.html",line:123,type:"fcn"};
this.def["PrintError"] = {file: "DAHostLib_rtw_c.html",line:128,type:"fcn"};
this.def["PrintWarning"] = {file: "DAHostLib_rtw_c.html",line:134,type:"fcn"};
this.def["GetErrorBuffer"] = {file: "DAHostLib_rtw_c.html",line:140,type:"fcn"};
this.def["GetNullPointer"] = {file: "DAHostLib_rtw_c.html",line:145,type:"fcn"};
this.def[")"] = {file: "DAHostLib_rtw_h.html",line:39,type:"type"};
this.def[")"] = {file: "DAHostLib_rtw_h.html",line:40,type:"type"};
this.def[")"] = {file: "DAHostLib_rtw_h.html",line:41,type:"type"};
this.def[")"] = {file: "DAHostLib_rtw_h.html",line:42,type:"type"};
this.def["HostLibrary"] = {file: "DAHostLib_rtw_h.html",line:62,type:"type"};
this.def["convertFromBus"] = {file: "slros_busmsg_conversion_cpp.html",line:6,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:13,type:"fcn"};
this.def["SLROSNodePtr"] = {file: "slros_initialize_cpp.html",line:3,type:"var"};
this.def["SLROSNodeName"] = {file: "slros_initialize_cpp.html",line:4,type:"var"};
this.def["Sub_toUdp_1201"] = {file: "slros_initialize_cpp.html",line:7,type:"var"};
this.def["Pub_toUdp_1220"] = {file: "slros_initialize_cpp.html",line:10,type:"var"};
this.def["slros_node_init"] = {file: "slros_initialize_cpp.html",line:12,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "/";
var isPC = false;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["toUdp_cpp.html"] = "../toUdp.cpp";
	this.html2Root["toUdp_cpp.html"] = "toUdp_cpp.html";
	this.html2SrcPath["toUdp_h.html"] = "../toUdp.h";
	this.html2Root["toUdp_h.html"] = "toUdp_h.html";
	this.html2SrcPath["toUdp_private_h.html"] = "../toUdp_private.h";
	this.html2Root["toUdp_private_h.html"] = "toUdp_private_h.html";
	this.html2SrcPath["toUdp_types_h.html"] = "../toUdp_types.h";
	this.html2Root["toUdp_types_h.html"] = "toUdp_types_h.html";
	this.html2SrcPath["toUdp_data_cpp.html"] = "../toUdp_data.cpp";
	this.html2Root["toUdp_data_cpp.html"] = "toUdp_data_cpp.html";
	this.html2SrcPath["multiword_types_h.html"] = "../multiword_types.h";
	this.html2Root["multiword_types_h.html"] = "multiword_types_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["DAHostLib_Network_c.html"] = "../../../../../MATLAB/toolbox/shared/spc/src_ml/extern/src/DAHostLib_Network.c";
	this.html2Root["DAHostLib_Network_c.html"] = "DAHostLib_Network_c.html";
	this.html2SrcPath["DAHostLib_Network_h.html"] = "../../../../../MATLAB/toolbox/shared/spc/src_ml/extern/include/DAHostLib_Network.h";
	this.html2Root["DAHostLib_Network_h.html"] = "DAHostLib_Network_h.html";
	this.html2SrcPath["DAHostLib_rtw_c.html"] = "../../../../../MATLAB/toolbox/shared/spc/src_ml/extern/src/DAHostLib_rtw.c";
	this.html2Root["DAHostLib_rtw_c.html"] = "DAHostLib_rtw_c.html";
	this.html2SrcPath["DAHostLib_rtw_h.html"] = "../../../../../MATLAB/toolbox/shared/spc/src_ml/extern/include/DAHostLib_rtw.h";
	this.html2Root["DAHostLib_rtw_h.html"] = "DAHostLib_rtw_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["slros_busmsg_conversion_cpp.html"] = "../slros_busmsg_conversion.cpp";
	this.html2Root["slros_busmsg_conversion_cpp.html"] = "slros_busmsg_conversion_cpp.html";
	this.html2SrcPath["slros_busmsg_conversion_h.html"] = "../slros_busmsg_conversion.h";
	this.html2Root["slros_busmsg_conversion_h.html"] = "slros_busmsg_conversion_h.html";
	this.html2SrcPath["slros_initialize_cpp.html"] = "../slros_initialize.cpp";
	this.html2Root["slros_initialize_cpp.html"] = "slros_initialize_cpp.html";
	this.html2SrcPath["slros_initialize_h.html"] = "../slros_initialize.h";
	this.html2Root["slros_initialize_h.html"] = "slros_initialize_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","toUdp_cpp.html","toUdp_h.html","toUdp_private_h.html","toUdp_types_h.html","toUdp_data_cpp.html","multiword_types_h.html","rtwtypes_h.html","rtmodel_h.html","DAHostLib_Network_c.html","DAHostLib_Network_h.html","DAHostLib_rtw_c.html","DAHostLib_rtw_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html","slros_busmsg_conversion_cpp.html","slros_busmsg_conversion_h.html","slros_initialize_cpp.html","slros_initialize_h.html"];
