function [xPIP_s,yPIP_s,zPIP_s] = findPIP_fun(CMC_AA,CMC_FE,MCP_AA,MCP_FE,l_dist,l_meta,xCMC,yCMC,zCMC)
%FINDPIP_FUN
%    [XPIP_S,YPIP_S,ZPIP_S] = FINDPIP_FUN(CMC_AA,CMC_FE,MCP_AA,MCP_FE,L_DIST,L_META,XCMC,YCMC,ZCMC)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    17-Feb-2018 21:06:25
[val, where] = min(abs(real(MCP_AA)));
MCP_AA = MCP_AA(where);

t2 = sin(CMC_AA);
t3 = cos(CMC_AA);
t4 = sin(CMC_FE);
t5 = cos(CMC_FE);
t6 = cos(MCP_AA);
t7 = t2.*t4.*6.123233995736766e-17;
t8 = t7-t3.*t5;
t9 = sin(MCP_AA);
t10 = t3.*t4.*6.123233995736766e-17;
t11 = t2.*t5.*3.749399456654644e-33;
t12 = t2+t10+t11;
t13 = cos(MCP_FE);
t14 = sin(MCP_FE);
xPIP_s = xCMC+l_dist.*t13.*(t6.*t8+t9.*t12)+l_dist.*t14.*(t2.*(-6.123233995736766e-17)+t2.*t5.*6.123233995736766e-17+t3.*t4-t8.*t9.*6.123233995736766e-17+t6.*t12.*6.123233995736766e-17)+l_meta.*t2.*t4.*6.123233995736766e-17-l_meta.*t3.*t5;
if nargout > 1
    t15 = t2.*t5;
    t16 = t10+t15;
    t17 = t3.*t5.*3.749399456654644e-33;
    t18 = t3-t7+t17;
    yPIP_s = yCMC-l_dist.*t13.*(t6.*t16+t9.*t18)+l_dist.*t14.*(t3.*6.123233995736766e-17+t2.*t4-t3.*t5.*6.123233995736766e-17-t6.*t18.*6.123233995736766e-17+t9.*t16.*6.123233995736766e-17)-l_meta.*t2.*t5-l_meta.*t3.*t4.*6.123233995736766e-17;
end
if nargout > 2
    t19 = t5.*6.123233995736766e-17;
    t20 = t19-6.123233995736766e-17;
    zPIP_s = zCMC-l_meta.*t4-l_dist.*t13.*(t4.*t6+t9.*t20)-l_dist.*t14.*(t5-t4.*t9.*6.123233995736766e-17+t6.*t20.*6.123233995736766e-17+3.749399456654644e-33);
end
