function [CMC_FE_s,CMC_AA_s] = findCMCAngles(K,CMC)
%FINDCMCANGLES
%    [CMC_FE_S,CMC_AA_S] = FINDCMCANGLES(KX,KY,KZ)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Feb-2018 18:09:50

%% Chose the solution whith the smaller Ky
% [val, where] = min(zk);
% Ky = yk(where);
% Kx = xk(where);
% Kz = zk(where);
% Ky = Ky(1);
% Kx = Kx(1);
% Kz = Kz(1);
% K = zeros(3,1);
% K(1) = Kx;
% K(2) = Ky;
% K(3) = Kz;


kx = K(1)-CMC(1);
ky = K(2)-CMC(2);
kz = K(3)-CMC(3);


t2 = kz.^2;
t3 = kx.^2;
t4 = ky.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
CMC_FE_s = -(pi/2 - acos(real(kz.*t6)));
if nargout > 1
    CMC_AA_s = pi-acos(real(kx.*t6.*1.0./sqrt(-t2./t5+1.0)));
    if K(2) > CMC(2)
        CMC_AA_s = -CMC_AA_s;
    end
end