%% With this script I calculate CMC-AA and CMC-FE angles.
% Firstly, it is supposed that CMC-AA and CMC-FE are incident and
% orthogonal. CMC-AA is directed as z (in the base frame) while CMC-FE is
% directed al x (in local axes)
syms qAA qFE kx ky kz
% kx, ky, kz are expressed in a reference system centred in CMC

d = sqrt(kx^2 + ky^2 + kz^2); % distance between K and CMC
T_CMC_AA = [cos(qAA), -sin(qAA), 0, 0; ...
            sin(qAA), cos(qAA) , 0, 0; ...
            0       , 0        , 1, 0; ...
            0       , 0        , 0, 1];
% T_CMC_FE = [1, 0       , 0        , 0; ...
%             0, cos(qFE), -sin(qFE), 0; ...
%             0, sin(qFE), cos(qFE) , 0; ...
%             0, 0       , 0        , 1];
        
T_CMC_FE = [cos(qFE), 0, sin(qFE), 0; ...
            0       , 1, 0       , 0; ...
           -sin(qFE), 0, cos(qFE), 0; ...
            0       , 0, 0       , 1];
        
T_d_K = [1, 0, 0, 0; ...
           0, 1, 0, 0; ...
           0, 0, 1, d; ...
           0, 0, 0, 1];

PAR_K = T_CMC_AA*T_CMC_FE*T_d_K*[0,0,0,1]';

eq = PAR_K(1:3,1) == [kx;ky;kz]
%%
qFE_s = solve(eq(3),qFE);

%%

[qFE_s,qAA_s,~,~] = solve(eq([1 2]), [qFE,qAA], 'ReturnConditions', true);

