function [xK_s,yK_s,zK_s,xPIP_s,yPIP_s,zPIP_s] = findAngles2_optimized
%FINDANGLES2_OPTIMIZED
%    [XK_S,YK_S,ZK_S,XPIP_S,YPIP_S,ZPIP_S] = FINDANGLES2_OPTIMIZED

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Feb-2018 18:44:13

xK_s = zeros(0,1);
if nargout > 1
    yK_s = zeros(0,1);
end
if nargout > 2
    zK_s = zeros(0,1);
end
if nargout > 3
    xPIP_s = zeros(0,1);
end
if nargout > 4
    yPIP_s = zeros(0,1);
end
if nargout > 5
    zPIP_s = zeros(0,1);
end
