function [xK_s,yK_s,zK_s,xPIP_s,yPIP_s,zPIP_s,MCP_FE_s,PIP_FE_s] = findAngles_optimized
%FINDANGLES_OPTIMIZED
%    [XK_S,YK_S,ZK_S,XPIP_S,YPIP_S,ZPIP_S,MCP_FE_S,PIP_FE_S] = FINDANGLES_OPTIMIZED

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    10-Feb-2018 12:20:35

xK_s = zeros(0,1);
if nargout > 1
    yK_s = zeros(0,1);
end
if nargout > 2
    zK_s = zeros(0,1);
end
if nargout > 3
    xPIP_s = zeros(0,1);
end
if nargout > 4
    yPIP_s = zeros(0,1);
end
if nargout > 5
    zPIP_s = zeros(0,1);
end
if nargout > 6
    MCP_FE_s = zeros(0,1);
end
if nargout > 7
    PIP_FE_s = zeros(0,1);
end
