afunction [xK_s,yK_s,xPIP_s,yPIP_s] = findAngles3_optimized
%FINDANGLES3_OPTIMIZED
%    [XK_S,YK_S,XPIP_S,YPIP_S] = FINDANGLES3_OPTIMIZED

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    11-Feb-2018 23:26:41

xK_s = zeros(0,1);
if nargout > 1
    yK_s = zeros(0,1);
end
if nargout > 2
    xPIP_s = zeros(0,1);
end
if nargout > 3
    yPIP_s = zeros(0,1);
end
